# Generated by Django 2.2.4 on 2024-07-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
